export default {
  content: ['./index.html', './src/**/*.{vue,ts}'],
  theme: {
    extend: {
      colors: {
        background: '#f9f9ff',
        surface: '#f9f9ff',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3fd',
        'surface-container': '#ecedf7',
        'surface-container-high': '#e6e8f2',
        'surface-container-highest': '#e0e2ec',
        'surface-variant': '#e0e2ec',
        'on-background': '#191c23',
        'on-surface': '#191c23',
        'on-surface-variant': '#414754',
        outline: '#727785',
        'outline-variant': '#c1c6d6',
        primary: '#005bbf',
        'primary-container': '#1a73e8',
        'primary-fixed': '#d8e2ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        secondary: '#595f65',
        'secondary-container': '#dde3eb',
        'on-secondary-container': '#5f656c',
        tertiary: '#9e4300',
        'tertiary-container': '#c55500',
        error: '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '16px',
        'container-max-width': '1280px',
        'sidebar-width': '280px',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
    },
  },
  plugins: [],
}
